server:
  port: 9527
spring:
  application:
    name: cloud-zuul-gateway
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true
zuul:
  ignored-services: '*'
  routes:
    mydept.serviceId: cloud-dept
    mydept.path: /mydept/**
info:
  app.name: cloud
  company.name: www.manyiaby.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$